version: "3"
services:

  server:
    build:
      context: ./src 
      dockerfile: ./Dockerfile 
    container_name: server
    depends_on:
      - mysql
    ports:
      - "80:8080"
    volumes:
      - "./src:/app/src"
    command: "npx nodemon -L src/server.js"

  mysql:
    image: mysql:5.7.31
    container_name: db 
    ports:
      - "3306:3306"
    volumes:
      - ./database/startScripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=admin
